#ifndef	__TB_RESOURCE_H__
#define __TB_RESOURCE_H__

#include "TB_type.h"

typedef enum tagLANG
{
	LANG_KOR,
	LANG_ENG,
} TB_LANG;

#define LANG_MIN	LANG_KOR
#define LANG_MAX	LANG_ENG

////////////////////////////////////////////////////////////////////////////////

typedef enum tagMSGID
{
	MSGID_ENTER_SETUP,
	MSGID_MASTERKEY,
	MSGID_PW_EQUAL,
	MSGID_PW_CHANGED,
	MSGID_PW_MUST_CHANGE,
	MSGID_LOGIN_FAIL,
	MSGID_LOGIN_RETRY_5MIN,
	MSGID_LOGIN_RETRY_REMAIN,
	MSGID_REBOOT_CANCELABLE,
	MSGID_REBOOT,
	MSGID_ACCOUNT_CLEAR,
	MSGID_INVERTER_CHANGE,
	MSGID_UNKNOWN,

	MSGID_MAX
} TB_MSGID;

typedef enum tagRESID
{
	RESID_MAIN_MENU_SETTING,
	RESID_MAIN_MENU_COMM_STATUS,	
	RESID_MAIN_MENU_ROLE,
	RESID_MAIN_MENU_WISUN_1ST,
	RESID_MAIN_MENU_WISUN_2ND,	
	RESID_MAIN_MENU_HISTORY,
	RESID_MAIN_MENU_TIME,
	RESID_MAIN_MENU_FACTORY,
	RESID_MAIN_MENU_FWUPDATE,	
	RESID_MAIN_MENU_MASTERKEY,
	RESID_MAIN_MENU_INFO,
	RESID_MAIN_MENU_REBOOT,
	RESID_MAIN_MENU_ADMIN_SETTING,

	RESID_MAIN_MENU_COMM_STATUS_UNDERBAR,

	////////////////////////////////////////////////////////////////////////////

	RESID_TLT_MAIN,				//	TLT : TITLE
	RESID_TLT_SETTING,
	RESID_TLT_COMM_STATUS,
	RESID_TLT_ROLE,
	RESID_TLT_WISUN_1ST,
	RESID_TLT_WISUN_2ND,
	RESID_TLT_HISTORY,
	RESID_TLT_LOG_COMM,
	RESID_TLT_LOG_SECURITY,
	RESID_TLT_LOG_COMM_DETAIL,
	RESID_TLT_LOG_SECU_DETAIL,
	RESID_TLT_TIME,
	RESID_TLT_FACTORY,
	RESID_TLT_DOWNLOAD,
	RESID_TLT_MASTERKEY,
	RESID_TLT_MASTERKEY_EDIT,
	RESID_TLT_MASTERKEY_LIB_INFO,
	RESID_TLT_BLANK,
	RESID_TLT_ADMIN_SETTING,
	RESID_TLT_DEBUG_MODE,
	RESID_TLT_PW_CHANGE,
	RESID_TLT_INFO,

	RESID_TLT_CHG_ADMIN_PW,
	RESID_TLT_CHG_USER_PW,
	RESID_TLT_LOGIN,

	////////////////////////////////////////////////////////////////////////////
	
	RESID_LBL_LOG_COMM,	
	RESID_LBL_LOG_SECURITY,
	
	RESID_LBL_INPUT_PW,			//	LBL : LABEL	
	RESID_LBL_PW_CURRENT,
	RESID_LBL_PW_NEW,
	RESID_LBL_PW_CONFIRM,
	
	RESID_LBL_MASTER_MDL,		//	MDL : MODULE
	RESID_LBL_REPEATER_MDL,
	RESID_LBL_SLAVE_MDL,

	RESID_LBL_ROLE_GGW,
	RESID_LBL_ROLE_FRTU1,
	RESID_LBL_ROLE_FRTU2,
	RESID_LBL_ROLE_FRTU3,
	RESID_LBL_ROLE_MID1,
	RESID_LBL_ROLE_MID2,
	RESID_LBL_ROLE_MID3,
	RESID_LBL_ROLE_REP,

	RESID_LBL_WISUN_INFO_1ST_MID,
	RESID_LBL_WISUN_INFO_1ST_FRTU,
	RESID_LBL_WISUN_INFO_1ST_GGW,
	RESID_LBL_WISUN_INFO_2ND_GGW,
	RESID_LBL_WISUN_INFO_2ND_REPEATER,
	RESID_LBL_WISUN_INFO_2ND_UNDERBAR,
	RESID_LBL_WISUN_INFO_BLANK,

	RESID_LBL_FACTORY,
	RESID_LBL_DOWNLOAD,

	RESID_LBL_ENABLE,
	RESID_LBL_OPMODE,
	RESID_LBL_MAX_CONN,
	RESID_LBL_FREQ,

	RESID_LBL_COMM_STATUS,
	RESID_LBL_COMM_RATE_DBM,

	RESID_LBL_MASTERKEY_EDIT,
	RESID_LBL_MASTERKEY_LIBINFO,

	RESID_LBL_MASTERKEY_LIB_NAME,
	RESID_LBL_MASTERKEY_LIB_INTERFACE_VERSION,
	RESID_LBL_MASTERKEY_LIB_VERSION,

	RESID_LBL_MASTERKEY_INPUT,
	RESID_LBL_MASTERKEY_UPLOAD,
	RESID_LBL_MASTERKEY_DOWNLOAD,

	RESID_LBL_ACCOUNT_SETTING,
	RESID_LBL_ACCOUNT_CLEAR,
	RESID_LBL_DEBUG_MODE,
	RESID_LBL_ACCOUNT_ADMIN,
	RESID_LBL_ACCOUNT_USER,

	RESID_LBL_INFO_FW_VER,
	RESID_LBL_INFO_VOLTAGE,
	RESID_LBL_INFO_EMS_DEST,
	RESID_LBL_INFO_SERIAL,
	RESID_LBL_INFO_MANUFACTURE,
	RESID_LBL_INFO_COT_IP,
	RESID_LBL_INFO_RT_PORT,
	RESID_LBL_INFO_FRTU_DNP,
	RESID_LBL_INFO_EMS_MODE,
	RESID_LBL_INFO_SESSION_UPDATE,

	RESID_LBL_FRTU_COM_SPEED,
	RESID_LBL_INVT_COM_SPEED,
	RESID_LBL_INVT_NUM,
	RESID_LBL_INVT_TIMEOUT,
	RESID_LBL_INVT_RETRY,
	RESID_LBL_INVT_READ_DELAY,
	RESID_LBL_INVT_WRITE_DELAY,
	RESID_LBL_AUTO_LOCK,
	RESID_LBL_OPTICAL_SENSOR,
	RESID_LBL_MASTER_COMM_MODE,
	RESID_LBL_SLAVE_COMM_MODE,

	////////////////////////////////////////////////////////////////////////////

	RESID_LOG_SECU_BOOT,                     //	SYSTEM LOG
	RESID_LOG_SECU_WATCHDOG,
	RESID_LOG_SECU_CONFIG,
	RESID_LOG_SECU_TIMESYNC,
	RESID_LOG_SECU_WORK_TIME,
	RESID_LOG_SECU_NORMAL_WORK,
	RESID_LOG_SECU_FWUPDATE_FAIL,
	RESID_LOG_SECU_FWUPDATE,
	RESID_LOG_SECU_FACTORY_FAIL,
	RESID_LOG_SECU_FACTORY,
	RESID_LOG_SECU_LOGIN_FAIL,
	RESID_LOG_SECU_LOGIN,
	RESID_LOG_SECU_PW_CHANGE_ADMIN,
	RESID_LOG_SECU_PW_CHANGE_USER,
	RESID_LOG_SECU_ERROR_FILE_SETUP,
	RESID_LOG_SECU_ERROR_FILE_LOG_COMM,
	RESID_LOG_SECU_ERROR_FILE_LOG_SECU,
	RESID_LOG_SECU_UNKNOWN,

	RESID_LOG_COMM_SUCCESS_GGW2FRTU,        //	COMMUNICATION LOG
	RESID_LOG_COMM_SUCCESS_GGW2REP,
	RESID_LOG_COMM_SUCCESS_FRTU2MID,
	RESID_LOG_COMM_FAIL_GGW2FRTU,
	RESID_LOG_COMM_FAIL_GGW2REP,
	RESID_LOG_COMM_FAIL_FRTU2MID,
	RESID_LOG_COMM_MODEM_DATA_ERROR,
	RESID_LOG_COMM_WISUN_DATA_ERROR,
	RESID_LOG_COMM_STATE_CHANGED,
	RESID_LOG_COMM_UNKNOWN,

	RESID_LOG_NO_DETAIL_DATA,               //	Detail for LOG
	RESID_LOG_DETAIL_TIME_SYNC,
	RESID_LOG_DETAIL_UNKNOWN,
	RESID_LOG_DETAIL_WORK_TIME,
	RESID_LOG_DETAIL_WATCHDOG_1,            //	Detail for WATCHDOG
	RESID_LOG_DETAIL_WATCHDOG_2,
	RESID_LOG_DETAIL_WATCHDOG_3,
	RESID_LOG_DETAIL_WATCHDOG_4,
	RESID_LOG_DETAIL_WATCHDOG_5,
	RESID_LOG_DETAIL_WATCHDOG_6,
	RESID_LOG_DETAIL_WATCHDOG_7,
	RESID_LOG_DETAIL_FILE_OPEN_ERROR,
	RESID_LOG_DETAIL_FILE_DATA_ERROR,
	RESID_LOG_DETAIL_FILE_READ_ERROR,
	RESID_LOG_DETAIL_FILE_WRITE_ERROR,

	////////////////////////////////////////////////////////////////////////////

	RESID_VAL_ENTER,
	RESID_VAL_ENABLE,
	RESID_VAL_DISABLE,
	RESID_VAL_HOUR,
	RESID_VAL_MINUTE,
	RESID_VAL_HIGH_VOLTAGE,
	RESID_VAL_LOW_VOLTAGE,

	////////////////////////////////////////////////////////////////////////////

	RESID_TIP_LEFT,
	RESID_TIP_RIGH,
	RESID_TIP_UP,
	RESID_TIP_DOWN,
	RESID_TIP_ESC,
	RESID_TIP_ENTER,
	
	RESID_TIP_LIST_HOME,
	RESID_TIP_LIST_END,
	RESID_TIP_LIST_LEFT,
	RESID_TIP_LIST_RIGHT,
	RESID_TIP_LIST_UP,
	RESID_TIP_LIST_DOWN,
	RESID_TIP_LIST_ENTER,

	RESID_UNKNOWN,

	RESID_MAX
} TB_RESID;

////////////////////////////////////////////////////////////////////////////////

extern char *TB_msgid_get_string( TB_MSGID mid );
extern char *TB_resid_get_string( TB_RESID rid );
extern TB_LANG TB_resid_get_lang( void );
extern void TB_resid_set_lang( TB_LANG lang );

#endif//__TB_RESOURCE_H__

